version: 0.2

phases:
  build:
    commands:
    #Install composer dependencies
      - |
        composer install \
        --no-progress \
        --ignore-platform-reqs
      
    #Build Nginx dockerfile
      - |
        docker build -f ./docker/nginx/Dockerfile

    #Build PHP dockerfile
      - |
        docker build -f ./docker/php/Dockerfile