version: 0.2

phases:
  build:
    run-as: root
    commands:
    #Install composer dependencies
      - |
        composer install \
        --no-progress \
        --ignore-platform-reqs
      
    #Build Nginx dockerfile
      - |
          docker build \
          -t nginx-biblioteca \
          -f ./docker/nginx/Dockerfile

    #Build PHP dockerfile
      - |
          docker build \
          -t php-biblioteca \
          -f ./docker/php/Dockerfile