version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
  build:
    run-as: root
    commands:
    #Install composer dependencies
      - |
        composer install \
        --no-progress \
        --ignore-platform-reqs
      
    #Build Nginx dockerfile
      - |
          docker build \
          -t "nginx-biblioteca" \
          -f ./docker/nginx/Dockerfile .

    #Build PHP dockerfile
      - |
          docker build \
          -t "php-biblioteca" \
          -f ./docker/php/Dockerfile .
  post_build:
    commands:
      - printf '[{"name":"container_name","imageUri":"image_URI"}]' > imagedefinitions.json
artifacts:
  files:
    - '**/*'
  base_directory: base_location
  name: biblioteca-tdd-$(date +%Y-%m-%d) 
  discard_paths: no