version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
  pre_build:
    run-as: root
    commands:
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    run-as: root
    commands:

    #Install composer dependencies
      - |
        composer install \
        --no-progress \
        --ignore-platform-reqs
      
    #Build Nginx dockerfile
      - |
          docker build \
          -t "nginx-biblioteca" \
          -f ./docker/nginx/Dockerfile .

    #Build PHP dockerfile
      - |
          docker build \
          -t "php-biblioteca" \
          -f ./docker/php/Dockerfile .
      - apt-get install jq -y
      - ContainerName="biblioteca-tdd"
      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
      - cat imageDetail.json
      - printf '{"name":"CONTAINER_NAME","imageUri":"IMAGE_URI"}' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json